deployExporterNode: false
deployGrafana: false
deployKubelets: false
deployKubeScheduler: false
deployKubeControllerManager: false
deployKubeState: false
deployAlertManager: false
deployKubeDNS: false
deployKubeEtcd: false

prometheus:
  storageSpec:
    volumeClaimTemplate:
      spec:
        # It's necessary to specify "" as the storageClassName
        # so that the default storage class won't be used, see
        # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
        storageClassName: ""
        volumeName: prometheus-persistent-volume
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10G
