topology_paths = [
  "example-topologies/2-single-node.yaml",
]

environments = [
  "NONE",
]

[istio]
build = false
hub = "docker.io/tahler"
tag = "tjberry"

[cluster]
create = false
name = "isotope-cluster-1"
zone = "us-central1-a"
version = "1.9.7-gke.3"

[server]
machine_type = "n1-standard-1"
disk_size_gb = 16
num_nodes = 1
image = "tahler/perf-test-service:latest"

[client]
machine_type = "n1-highcpu-4"
disk_size_gb = 16
image = "tahler/fortio:prometheus"
# The last argument, the URL to send traffic to, is automatically inserted.
qps = "max"
duration = "3s"
num_concurrent_connections = 16
