topology_paths = [
  "example-topologies/0-canonical.yaml",
]

environments = [
  "NONE",
  "ISTIO",
]

[istio]
build = false
hub = "docker.io/tahler"
tag = "tjberry"

[cluster]
create = false
name = "isotope-cluster-197"
zone = "us-west1-a"
version = "1.9.7-gke.3"

[server]
machine_type = "n1-standard-1"
disk_size_gb = 16
num_nodes = 3
image = "tahler/perf-test-service:latest"

[client]
machine_type = "n1-highcpu-16"
disk_size_gb = 16
image = "istio/fortio:1.0.0"
# The last argument, the URL to send traffic to, is automatically inserted.
args = [
  "load",
  "-json=-",
  "-c=32", # 32 concurrent connections
  "-qps=0", # max QPS
  "-t=5m", # run for 5 minutes
]
