topology_paths = [
  "../example-topologies/0-0-canonical.yaml",
]

environments = [
  "NONE",
  "ISTIO",
]

[cluster]
project_id = "istio-200620"
# Cluster will be created with one n1-standard-1 node in the default node-pool
# running Prometheus. In total, the cluster will have 1 Prometheus node, 1
# client node, and N service-graph nodes (total of N + 2 nodes).
name = "isotope-cluster-1"
zone = "us-central1-a"
version = "1.9.7-gke.3"

[istio]
archive_url = "https://storage.googleapis.com/istio-prerelease/daily-build/release-1.0-20180716-12-45/istio-release-1.0-20180716-12-45-linux.tar.gz"

[server]
machine_type = "n1-standard-1"
disk_size_gb = 16
num_nodes = 4
image = "tahler/mock-service:latest"

[client]
machine_type = "n1-standard-16"
disk_size_gb = 16
image = "tahler/fortio:prometheus"
qps = "max"
duration = "5m"
num_concurrent_connections = 64
