topology_paths = [
  "500-svc_1000-end.yaml",
]

environments = [
  # "NONE",
  "ISTIO",
]

[cluster]
project_id = "istio-200620"
# Cluster will be created with one n1-standard-4 node in the default node-pool
# running Prometheus. In total, the cluster will have 1 Prometheus node, 1
# client node, and N service-graph nodes (total of N + 2 nodes).
name = "cluster-l"
zone = "us-central1-a"
version = "1.10.4-gke.2"

[istio]
archive_url = "https://github.com/istio/istio/releases/download/1.0.0/istio-1.0.0-linux.tar.gz"

[server]
# With a limit of 1 vCPU per service, 0.1 vCPU per sidecar, and 1 vCPU per
# component (pilot, telemetry, policy, etc.):
# vCPUs >= 10 + num_sidecars * 1.1
machine_type = "n1-standard-32"
num_nodes = 48
disk_size_gb = 16
image = "tahler/mock-service:kube"

  # [server.resource_limits]
  # cpu = "1"
  # mem = "3.75G"

[client]
machine_type = "n1-standard-16"
disk_size_gb = 16
image = "tahler/fortio:prometheus"
qps = "1000"
duration = "5m"
num_concurrent_connections = 64
