topology_paths = [
  "../example-topologies/0-0-canonical.yaml",
]

environments = [
  "NONE",
  "ISTIO",
]

[istio]
archive_url = "https://storage.googleapis.com/istio-prerelease/daily-build/release-1.0-20180716-12-45/istio-release-1.0-20180716-12-45-linux.tar.gz"

[server]
image = "tahler/mock-service:latest"

[client]
image = "tahler/fortio:prometheus"
qps = "max"
duration = "5m"
num_concurrent_connections = 64
